### PR TITLE
Added lighter colors for ligth theme

### PR DESCRIPTION
**Pull request by oscarmolinadev**
Added lighter colors and consistent colors for heads/subheads for light theme.

### CODE REVIEW

**Comment by awoolstrum** [comment]
Hey I didn't see this until just now!  I'm excited to merge it in.  :)

**Comment by awoolstrum** [comment]
Ok I've pushed it out.  @oscarmolinadev If you don't mind, what's your forum name so I can give you credit?

**Comment by oscarmolinadev** [comment]
Thanks! My name in forum is: OMSmolina

**Comment by awoolstrum** [comment]
Cool!  I'll build it into the readme (ie i'll make a readme... :P ) next publish too.

**Pull request merged**
